name: Build and Deploy Static Web App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust if using a different Node version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build  # Assuming this generates the build folder

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v0
        id: deploy-to-azure
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"  # Source files (e.g., React source code)
          output_location: "build"  # Build output directory for React
